name: PhotoDeck

on:
  push:
    branches: [main-sub, dev]
  pull_request:
    branches: [dev ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
    
    - run: npm ci
    - run: npm run lint

  